### ISSUE TITLE
[iOS] Create Tests and Documentation of Scan

### ISSUE THREAD

**Issue by JesseMonteiro** [tiki/capture-receipt-capacitor#198]
Physical Roadmap

Scan()
    
    Input - None
    
    Output - None
    
    Expected Failures
    - Falha ao fornecer acesso à câmera
      - Call.reject("Please provide camera access.")

**Comment by ricardobrg** [comment]
@JesseMonteiro 
This test should invoke the BRScanResultsDelegate and add tests for 
didFinishScanning
didCancelScanning
scanningErrorOccurred
