### ISSUE TITLE
Benchmark Microblink

### ISSUE THREAD

**Issue by JesseMonteiro** [tiki/capture-receipt-capacitor#272]
### Reason

Delay on microblink requisition 

### Description

We need know the time of microblink requisition 

### Success Criteria

- [x] Benchmark with few orders
- [ ] Benchmark with alot of orders

**Comment by Schuler-Gabriel** [comment]
| Marks | Android | IOS |
| ------ | -------- | --- | 
| 1 day | 00:35:42 | 00:00:00|
