### ISSUE TITLE
Test Google IMAP login in Android

### ISSUE THREAD

**Issue by ricardobrg** [tiki/capture-receipt-capacitor#273]
### Reason

The user needs to login with IMAP to scrape receipts from Gmail

### Description

There is a known issue with iOS IMAP login. The Microblink SDK creates a webview for the user to create an app password for Gmail login. After the app password is created, the webview does not dismiss automatically, and the only option for the user is to cancel the login.

During manual testing we faced the same issue on Android, which was working before. We need to verify if it has the same cause or if the error is in our side.

### Success Criteria

- [ ] Reproduce the login error on Android or login

**Comment by mike-audi** [comment]
Pretty sure this is the android issue but I'm not quite done testing.

line 96 in Email.kt

`ProviderSetupResults.CREATED_APP_PASSWORD -> call.reject("CREATED_APP_PASSWORD")`

we don't want to reject the call when an app password is created. you can log it to .d or ignore it completely

**Comment by ricardobrg** [comment]
The Google IMAP login is working in Android with US email account. It does not work with Gmail BR account.

**Comment by ricardobrg** [comment]
The error remains. It is tracked in tiki/apps-receipt-capacitor/issues/192
