### ISSUE TITLE
[TS] Use listeners to receive scan results

### ISSUE THREAD

**Issue by MiroBenicio** [tiki/capture-receipt-capacitor#275]
### Reason

To handle correctly with the scan method

### Description

As a developer
I need to change the scan method architecture to handle with more than one receipt from the scan method

### what it is now 
The scan method just catch one receipt from the plugin

### what it should be
Should use an callbacks and a runs an asynchronous handler to load all receipt data without errors

### Success Criteria

- [ ] Receipts are received in the listener

**Comment by ricardobrg** [comment]
This implementation should be done in TypeScript and native code.

In TypeScript the `PluginListenerHandle` should be used. 
[TypeScript the BrowserPlugin implementation](https://github.com/ionic-team/capacitor-plugins/blob/main/browser/src/definitions.ts#L20-L29)
In Android and iOS use `notifyListeners` in `Plugin` 
[Android BrowserPlugin implementation](https://github.com/ionic-team/capacitor-plugins/blob/main/browser/android/src/main/java/com/capacitorjs/plugins/browser/BrowserPlugin.java)
[iOS BrowserPlugin implementation](https://github.com/ionic-team/capacitor-plugins/blob/main/browser/ios/Plugin/BrowserPlugin.swift)
