### ISSUE TITLE
[iOS] Define the value of DayCutOff and DaysToStoreReceiptData

### ISSUE THREAD

**Issue by JesseMonteiro** [tiki/capture-receipt-capacitor#294]
### Reason

We need to decide the period of time

### Description

The value of DayCutOff is the period of look back time in an scan(GrabOrders), and DaysToStoreReceiptData is the period of time what the data of an scan will be stored locally in the phone of the user for not scan agin the same receipt

### Success Criteria

- [ ] Define DayCutOff
- [ ] Define DaysToStoredReceiptData

**Comment by ricardobrg** [comment]
#354 will handle it
