### ISSUE TITLE
Send a notification when IMAP errors happens

### ISSUE THREAD

**Issue by MiroBenicio** [tiki/capture-receipt-capacitor#306]
### Reason

Inform the user about any IMAP errors

### Description

Fire a notification using the capacitor local notification api when a IMAP errors happens

### Success Criteria

- [ ] a working local notification fired to the user after an IMAP error happen

**Comment by ricardobrg** [comment]
see https://github.com/tiki/capture-receipt-capacitor/issues/305#issuecomment-1774948205
