### ISSUE TITLE
[UI] Add password field for email account logout

### ISSUE THREAD

**Issue by ricardobrg** [tiki/capture-receipt-capacitor#318]
**NOTE:  Before beginning to work on this story. First investigate why/how the Microblink demo app is able to logout of IMAP without prompting for a password.**

### Reason

Email account logout requires password

### Description

When the user clicks the minus button to remove an IMAP email account it should open a form with the username prefilled, so the user can input the password which is required for logging out from email accounts.

It is not required for OAuth emails or Retailer accounts since the logout is handled by OAuth.

### Success Criteria

- [ ] UX definition
- [ ] UI implementation
- [ ] After the user taps the minus button, the password form is showed
- [ ] After the user submits the form, the email account does not show in the UI
- [ ] After the user submits the form, the email account is not returned by the plugin accounts method

**Comment by timoguin** [comment]
Are we 100% sure the password is required when logging out? Microblink's IMAP demo app does not prompt for a password when logging out.

Let's be absolutely sure this is necessary before making any UX changes.

**Comment by ricardobrg** [comment]
Microblink's IMAP function requires the password to logout. And the SDK stores this password encrypted. Our solution was to retrieve the account password on logout. Implemented in #329
