### ISSUE TITLE
Callbacks for repeated delivery are closed before completion 

### ISSUE THREAD

**Issue by mike-audi** [tiki/capture-receipt-capacitor#335]
### Reason

Callbacks for repetitive actions (account, receipt) are closed before before the transaction is complete causing the app layer to miss results

### Description

I only get the callback for 1 receipt/account, after that i get No callback registered. Skipping callback:

The issue is in the fire method in callback-mgr. It's because we remove the callback from the map once it's triggered, when we should be waiting until onComplete or onError to remove it. Since they share a request id, it should be trivial to fix (I may even do it tonight after I eat dinner). We do need to check both maps, because we share onComplete and onError (we should change this soon, it's a bad design as is). 

### Success Criteria

- [ ] fire the callback for every event
- [ ] remove the callback when the transaction is complete
- [ ] depending how errors are handled, the callback should possibly also be removed onError

**Comment by ricardobrg** [comment]
moved to #340
