### ISSUE TITLE
[Android] Set latestOrdersOnly True 

### ISSUE THREAD

**Issue by mike-audi** [tiki/capture-receipt-capacitor#346]
### Reason

On sequential scans, we do not want to return already scanned receipts

### Description

Per Microblink's docs

[Latest Orders Only](https://blinkreceipt.github.io/blinkreceipt-android/configuring_client_alp/#latest-orders-only)

The latestOrdersOnly property specifies at what point the SDK stops searching for orders.

Example: dayCutoff is set to 14 days, and you retrieve orders. After that, you set the dayCutoff to 28 days. If latestOrdersOnly is set to true, you will only get orders which are newer than the latest order you received the first time. If it is set to false, you will also get orders which are older than those you got when retrieving orders with a 14 days cutoff, and at the same time inside the 28-day window.

You can specify this with the latestOrdersOnly property on the AccountLinkingClient instance, i.e.:

```
val client = AccountLinkingClient(context)
client.latestOrdersOnly = false
```

The property latestOrdersOnly is set to true by default, which means you will only get orders newer than the most recent order you’ve received. If it’s the first time you’re retrieving orders, you will get all orders inside the cutoff window.

### Success Criteria

- [ ] client.latestOrdersOnly = true

**Comment by ricardobrg** [comment]
implemented in #350
