### ISSUE TITLE
[Android & IOS] The app is not receiving receipts from the retailer

### ISSUE THREAD

**Issue by Schuler-Gabriel** [tiki/capture-receipt-capacitor#410]
### Reason

The app is not receiving receipts from the retailer

### Description

if you login an amazon account and a gmail one, the app will only receive receipts from the email and the onComplete is never returned.

### Success Criteria

- [ ] We should receive receipts both from IMAP and retailers

**Comment by JesseMonteiro** [comment]
In iOS i receive 17 receipts of Microblink and no one was accept, this is the output.
<img width="1373" alt="Captura de Tela 2023-10-12 às 15 44 11" src="https://github.com/tiki/capture-receipt-capacitor/assets/8730443/4f11055d-f5e8-432b-8d6f-837b3e0d77ec">


and the log of xcode
⚡️  TO JS {"verified":true,"source":"GMAIL","username":"jessemonteiroferreira@gmail.com"}
⚡️  To Native ->  Preferences set 30007788
⚡️  TO JS undefined
⚡️  To Native ->  CaptureReceipt scan 30007789
⚡️  To Native ->  TikiSdk getPayables 30007790
invoke method
⚡️  TO JS {"payables":[]}
⚡️  TO JS {"payload":{"instacartShopper":false,"fraudulent":false,"products":[[{"subProducts":[],"unitOfMeasure":"","productNumber":"","blinkReceiptCategory":"Electronics|Computers|Hard Drives, SSD & Storage","fullPrice":0,"probability":0,"additionalLines":[],"descr
⚡️  TO JS {"payload":{"loyaltyProgram":false,"receiptTime":"23:27","currencyCode":"USD","blinkReceiptId":"A2542426-89E6-4872-8133-B0FC33FBB64F","qualifiedPromotions":[[]],"products":[[{"subProducts":[],"quantity":1,"blinkReceiptCategory":"Household Essentials|Househ
⚡️  TO JS {"payload":{"instacartShopper":false,"duplicateBlinkReceiptIds":[],"tip":0,"subtotal":0,"coupons":[[{"unitOfMeasure":"","quantity":1,"possibleProducts":[],"sensitive":false,"fullPrice":0,"voided":false,"subProducts":[],"productNumber":"","priceAfterCoupons
⚡️  TO JS {"event":"onReceipt","payload":{"merchantSources":[],"eReceiptEmailSubject":"Novidades no Disney+","eReceiptShippingCosts":0,"coupons":[[]],"ocrConfidence":0,"eReceiptEmailProvider":"gmail","shipments":[[]],"paymentMethods":[[]],"tip":0,"unqualifiedPromoti
⚡️  TO JS {"payload":{"duplicateBlinkReceiptIds":[],"retailerId":11365,"eReceiptMerchantEmail":"transaction@notice.aliexpress.com","unqualifiedPromotions":[[]],"eReceiptAuthenticated":false,"eReceiptEmailSubject":"Pedido 8176479394882015: confirmação de compra","sub
⚡️  TO JS {"event":"onReceipt","payload":{"products":[[{"probability":0,"possibleProducts":[],"unitPrice":290.6199951171875,"voided":false,"unitOfMeasure":"","subProducts":[],"priceAfterCoupons":290.6199951171875,"added":false,"fullPrice":0,"totalPrice":290.61999511
⚡️  TO JS {"event":"onReceipt","payload":{"merchantSources":[],"eReceiptEmailSubject":"Pedido 8176479394882015: atualização de entrega","eReceiptShippingCosts":0,"coupons":[[{"productNumber":"","additionalLines":[],"fullPrice":0,"possibleProducts":[],"unitOfMeasure"
⚡️  TO JS {"payload":{"qualifiedPromotions":[[]],"foundTopEdge":false,"loyaltyProgram":false,"eReceiptComponentEmails":[[]],"fraudulent":false,"paymentMethods":[[]],"eReceiptEmailProvider":"gmail","merchantSources":[],"receiptTime":"09:12","products":[[]],"subtotalM
⚡️  TO JS {"payload":{"currencyCode":"USD","qualifiedPromotions":[[]],"foundTopEdge":false,"eReceiptFulfilledBy":"Aliexpress.com","loyaltyProgram":false,"eReceiptEmailProvider":"gmail","eReceiptComponentEmails":[[]],"paymentMethods":[[]],"total":0,"merchantSources":
[Capacitor Plugin Error] - CaptureReceipt - addListener - Unable to serialize plugin response as JSON.Ensure that all data passed to success callback from module method is JSON serializable!
⚡️  TO JS {}
⚡️  TO JS {"payload":{"coupons":[[{"unitOfMeasure":"","description":"<BRProduct: 0x153f71e50>","additionalLines":[],"totalPrice":290.6199951171875,"quantity":1,"subProducts":[],"fullPrice":0,"possibleProducts":[],"unitPrice":290.6199951171875,"sensitive":false,"prod
⚡️  TO JS {"payload":{"eReceiptComponentEmails":[[]],"eReceiptAuthenticated":false,"shipments":[[]],"unqualifiedPromotions":[[]],"coupons":[[]],"duplicateBlinkReceiptIds":[],"paymentMethods":[[]],"merchantSources":[],"productsPendingLookup":0,"receiptDate":"10\/06\/
⚡️  TO JS {"requestId":"bdd32c66-6bc5-4b45-ac51-6fc17fbe815e","event":"onReceipt","payload":{"foundBottomEdge":false,"foundTopEdge":false,"eReceiptShippingCosts":0,"tip":0,"eReceiptComponentEmails":[[]],"merchantSources":[],"eReceiptRawHtml":"<div style=\"padding-bo
⚡️  TO JS {"requestId":"bdd32c66-6bc5-4b45-ac51-6fc17fbe815e","event":"onReceipt","payload":{"eReceiptComponentEmails":[[]],"eReceiptAuthenticated":false,"shipments":[[]],"unqualifiedPromotions":[[]],"coupons":[[]],"duplicateBlinkReceiptIds":[],"paymentMethods":[[]]
⚡️  TO JS {"payload":{"foundBottomEdge":false,"blinkReceiptId":"0ECCF4A6-BFBC-4823-B0BA-2BC31C745D5B","qualifiedPromotions":[[]],"merchantSources":[],"eReceiptComponentEmails":[[]],"fraudulent":false,"shipments":[[]],"instacartShopper":false,"tip":0,"duplicateBlinkR
⚡️  TO JS {"event":"onReceipt","payload":{"coupons":[[]],"loyaltyProgram":false,"eReceiptEmailSubject":"[Nintendo Account] New sign-in","receiptDate":"10\/07\/2023","qualifiedPromotions":[[]],"receiptTime":"15:07","productsPendingLookup":0,"paymentMethods":[[]],"fou
⚡️  TO JS {"event":"onReceipt","payload":{"subtotalMatches":false,"eReceiptEmailSubject":"Pedido 8176479394882015: alfândega concluída","duplicateBlinkReceiptIds":[],"duplicate":false,"loyaltyProgram":false,"merchantSources":[],"eReceiptMerchantEmail":"transaction@n
⚡️  [debug] - Invalid receipt: Invalid retailerId: 11365
⚡️  [debug] - Invalid receipt: Invalid retailerId: 10050
⚡️  [debug] - Invalid receipt: Invalid retailerId: 11365
⚡️  [debug] - Invalid receipt: Invalid retailerId: 0
⚡️  [debug] - Invalid receipt: Invalid retailerId: 11365
⚡️  [debug] - Invalid receipt: Invalid retailerId: 11365
⚡️  [debug] - Invalid receipt: Invalid retailerId: 11365
⚡️  [debug] - Invalid receipt: Invalid retailerId: 0
⚡️  [debug] - Invalid receipt: Invalid retailerId: 11365
⚡️  [debug] - Invalid body. Skipping callback: {}
⚡️  [debug] - Invalid receipt: Invalid retailerId: 11365
⚡️  [debug] - Invalid receipt: Invalid retailerId: 0
⚡️  [debug] - Invalid receipt: Invalid retailerId: 0
⚡️  [debug] - Invalid receipt: Invalid retailerId: 0
⚡️  [debug] - Invalid receipt: Invalid retailerId: 0
⚡️  [debug] - Invalid receipt: Invalid retailerId: 0
⚡️  [debug] - Invalid receipt: Invalid retailerId: 0

**Comment by mike-audi** [comment]
@JesseMonteiro

This issue is definitely related to serialization of receiptIds

see line 23 in RspReceipt.swift `private let retailerId: UInt`

now compare this to line 34 in RspReceipt.kt `private val retailerId: JSRetailer` where we return
```
    private val id: Int
    private val bannerId: Int
```

**Comment by mike-audi** [comment]
At first glance it looks like Microblink handles this differently for iOS & Android: 
https://blinkreceipt.github.io/blinkreceipt-ios/Classes/BRScanResults.html

**Comment by Schuler-Gabriel** [comment]
here a list of the serialization differences between android and IOS:
   * RetailerId:
      *Android: is an object with id and bannerId properties
      *IOS: is an Int
   * Many fields are typed as JS[type]Type in android because they are an object with a "value" with the same type as the name and a "confidence" being a float. in IOS we only have the value and is not an object:
      * Android: 
      {
        receiptDate: {
             confidence: float,
             value: String
       }
     }
   * IOS: receiptDate: String
   * the fields with that problem are:
[ ] receiptDate
[ ] receiptTime
[ ] retailerId
[ ] total
[ ] tip
[ ] subtotal
[ ] taxes
[ ] storeNumber
[ ] merchantName
[ ] storeAddress
[ ] storeCity
[ ] storeState
[ ] storeZip
[ ] storeCountry
[ ] storePhone
[ ] cashierId
[ ] transactionId
[ ] registerId
[ ] taxId
[ ] mallName
[ ] last4cc
[ ] longTransactionId
[ ] merchantMatchGuess
[ ] purchaseType
[ ] channel
[ ] paymentTerminalId
[ ] paymentTransactionId
[ ] combinedRawText
