### ISSUE TITLE
Downgrade UUID library to 8.3.0

### ISSUE THREAD

**Issue by mike-audi** [tiki/capture-receipt-capacitor#460]
### Reason

9.x is creating issues with customer integration

### Description

Version 9.x of the UUID library uses the new crypto apis which causes can cause issues in some customer stacks. 

### Success Criteria

- [ ] UUID lib 8.x implemented

**Comment by ricardobrg** [comment]
We could use a different unique id for the requests too, without external dependencies. We just use the uuid to identify the requests and its callbacks.
