### ISSUE TITLE
Compile Backend Components Documentation

### ISSUE THREAD

**Issue by sfaria27** [tiki/capture-receipt-capacitor#477]
As a team member, I need to compile documentation on the backend components of the email scrape feature for the high-level system overview. This documentation will offer insights into the architecture and functionality of the backend system.

**Comment by ricardobrg** [comment]
# E-mail Receipt Submission Process Documentation

## 1. Verify Data Provider Identity and Data Integrity

### What:
We ensure the authenticity of the data provider and verify the integrity of the submitted data.

### How:
- Data provider identity is verified using the JSON Web Token (JWT) received with the request.
- JWT is obtained from TIKI Auth and used for authentication with TIKI Data Provider API during receipt email upload.

### Systems Involved:
- Data provider requests JWT from TIKI Auth.
- TIKI Data Provider API authenticates using the JWT to verify identity.

## 2. Check User's License

### What:
We validate if the data provider possesses a valid license for the user data.

### How:
- TIKI Data Provider API checks license validity using the TIKI License API
- Requests without a valid license or expired licenses are rejected.

### Systems Involved:
- TIKI Data Provider API communicates with TIKI License API to verify the data provider's license.

## 3. Create a Request Record

### What:
We generate a unique ID for tracking and future reference.

### How:
- TIKI Data Provider API creates a unique request ID for each submission.
- An HTTP response includes this ID for user reference.

### Systems Involved:
- TIKI Data Provider API generates and returns the request ID.

## 4. Extract Text from the e-mail

### What:
We parse the information of the email body and the email attachments into combined structured receipt data.

### How:
- The e-mail body is analyzed byt TIKI Data Provider API to detect receipt data.
- TIKI Data Provider API authenticates with [Amazon Textract](https://aws.amazon.com/textract/) using [temporary credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) through [AWS IAM](https://aws.amazon.com/iam/).
- The attachments are sent to [Amazon Textract](https://aws.amazon.com/textract/), and the extracted text is returned.
- The data obtained from the attachments and the e-mail body is combined into structured data.
- Email data is retained in ephemeral memory until extraction is complete, then discarded.

### Systems Involved:
- TIKI Data Provider API authenticates with [Amazon Textract](https://aws.amazon.com/textract/) using [AWS IAM](https://aws.amazon.com/iam/).
- [Amazon Textract](https://aws.amazon.com/textract/) employs [AWS Infrastructure Security](https://docs.aws.amazon.com/textract/latest/dg/infrastructure-security.html), and data is not stored post-extraction.

## 5. Convert Text to Receipt Data

### What:
We convert the extracted text into structured Receipt Data for ingestion into TIKI Ocean.

### How:
- TIKI Data Provider API sends the extracted text to TIKI Writer for conversion into TIKI Ocean formatted data.
- Text data is retained in ephemeral memory until the conversion is complete, then discarded.

### Systems Involved:
- TIKI Data Provider API forwards extracted text to TIKI Writer for conversion.

## 6. Publish Receipt Data to TIKI Ocean

### What:
Receipt data is transmitted to TIKI Ocean, and the request record is updated.

### How:
- TIKI Writer sends the formatted data to TIKI Ocean for publication.
- The request record created in step 3 is updated to reflect the publication status.

### Systems Involved:
- TIKI Writer transmits formatted data to TIKI Ocean.
- TIKI Data Provider API updates the request status to "published."
