### ISSUE TITLE
Create Block Diagram for Data Flow

### ISSUE THREAD

**Issue by sfaria27** [tiki/capture-receipt-capacitor#479]
As a team member, I need to design and create a block diagram that visually represents the flow of data from the scrape to the sale, supplementing the existing data flow documentation. Each block in the diagram should correspond to a stage in the data flow, referencing the previous documentation, and include privacy and security information.

## Acceptance Criteria
- Develop a block diagram illustrating the flow of data from scrape to sale.
- Each block in the diagram corresponds to a documented stage in the data flow.
- Include references to the relevant sections in the previous data flow documentation for each block.
- Provide clear descriptions for each block, summarizing its role in the data flow.
- Document privacy and security considerations specific to each block.

**Comment by ricardobrg** [comment]
@sfaria27  
[email_data_flow.pdf](https://github.com/tiki/capture-receipt-capacitor/files/13793277/email_data_flow.pdf)
