### ISSUE TITLE
[Android] Close WebView after authentication

### ISSUE THREAD

**Issue by Schuler-Gabriel** [tiki/capture-receipt-capacitor#84]
As a user,
I need the WebView to close after I authenticate my account

What it is now

The user have to close the WebView manually

What it should be

After the authentication the WebView closes automatically

Acceptance criteria
After the authentication the WebView closes automatically

**Comment by ricardobrg** [comment]
@Schuler-Gabriel Let's check their example project implementation https://github.com/BlinkReceipt/blinkreceipt-android/blob/master/blinkreceipt-demo/BlinkReceiptAccountLinking/src/main/java/com/blinkreceipt/linking/MainActivity.java
